### ISSUE TITLE
Cannot Load DLL

### ISSUE THREAD

**Issue by IndigoCarmine** [insinfo/pdf_text_extraction#1]
Hello!
Invalid argument(s): Failed to load dynamic library 'pdftotext.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)   
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      new PDFToTextWrapping (package:pdf_text_extraction/src/pdf_to_text_wrapping.dart:30:34)

This error came from that Directory.current.path is not lib path.
(If I'm not using it incorrectly.)

Could you revise it, please?

**Comment by insinfo** [comment]
download this DLL and pass it to the code as demonstrated in the README
https://github.com/insinfo/pdf_text_extraction/blob/main/pdftotext.dll

**Comment by insinfo** [comment]
this error 126 could be incorrect dll path or missing Microsoft C++ Runtime 2005-2019-2022

**Comment by IndigoCarmine** [comment]
2023年5月31日(水) 0:18 Isaque Neves ***@***.***>:
